#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
# backing up the default settings 
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

echo '
frontend stevebanks03.tech
        bind *:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 137909-web-01 174.129.54.207:80 check
        server 137909-web-02 54.208.55.182:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
